### ISSUE TITLE
MG::Text does not trigger on_touch callback?

### ISSUE THREAD

**Issue by andrewhavens** [HipByte/motion-game#35]
According to the documentation, the `MG::Text` inherits an `on_touch` method (from `MG::Widget`) that accepts a block which is supposed to be called when the widget is tapped. However, nothing happens when I tap on the text. However, when I changed the object to an `MG::Button` it worked without modification, which makes me think that `MG::Text` does not actually trigger the `on_touch` callback.

**Comment by eichert12** [comment]
MG::Text is a subclass of the UIWidget class in Cocos-2d. UIWidget defaults to having touch disabled.  UIButton in Cocos-2d enables touch which is why MG::Button is working but MG::Text isn't.  Ideally the Widget class would expose a touch_enabled property that could be set to true and make on_touch work for MG::Text and other Widgets.  I'm going to take a look at the source to see if I can determine what changes would be necessary.

**Comment by eichert12** [comment]
#37 adds touch_enabled? and touch_enabled= which allows the on_touch event handler to be supported for MG::Text (as well as other widgets that don't have touch enabled defaulted to true).

**Comment by eichert12** [comment]
This is fixed with the merge of #37
