### ISSUE TITLE
Incorrect documentation generated by RubyDoc

### ISSUE THREAD

**Issue by andrewhavens** [HipByte/motion-game#62]
@Watson1978 I noticed that some of your recent changes to the documentation now result in incorrect documentation.

Incorrectly generated: http://www.rubydoc.info/gems/motion-game/
Correctly generated, but outdated: http://www.rubymotion.com/developers/motion-game/_index.html

<img width="443" alt="screen shot 2016-12-10 at 10 58 53 pm" src="https://cloud.githubusercontent.com/assets/446392/21078660/42883a22-bf2c-11e6-998c-47b6ca2c9d52.png">

**Comment by Watson1978** [comment]
Related to https://github.com/HipByte/motion-game/commit/149cdec9be1da1243e74240aee3ad161bcdf9990

When I will push new version, new document will be generated in http://www.rubydoc.info/gems/motion-game/, I hope.

Because looks like http://www.rubymotion.com/developers/motion-game/_index.html is not updated since first version.

**Comment by andrewhavens** [comment]
Ah okay, I understand.

**Comment by Watson1978** [comment]
NEW reference is in http://www.rubydoc.info/gems/motion-game/1.1.7.2/

**Comment by andrewhavens** [comment]
Awesome! Thanks @Watson1978!
